CREATE TABLE IF NOT EXISTS RecordID(
id INTEGER PRIMARY KEY,
name VARCHAR(10));

INSERT INTO RecordID (name) VALUES ('REC001');
INSERT INTO RecordID (name) VALUES ('REC011');
INSERT INTO RecordID (name) VALUES ('REC020');


